---

storage:
  type: "nfs"  # Options: local, nfs
  nfs:
    server: "192.168.1.5"
    export_path: "/export/dev_data"
    mount_path: "/cockroachdb/data"
    log_path: "/cockroachdb/logs"
    opts: "rw,sync,soft,timeo=30,retrans=2"
    rabbitmq_path: "/rabbitmq"
  local:
    mount_path: "/var/lib/cockroachdb/data"
    log_path: "/var/lib/cockroachdb/logs"
    rabbitmq_path: "/var/lib/rabbitmq"

system:
  swappiness: 1
  max_file_descriptors: 65536
  transparent_hugepages: "never"
  max_map_count: 262144
  io_scheduler: deadline
  cpu_governor: performance
  numa_balancing: 0
  kernel_shmmax: 68719476736
  kernel_shmall: 4294967296
  network_buffers:
    rmem_max: 16777216
    wmem_max: 16777216
    tcp_rmem: "4096 87380 16777216"
    tcp_wmem: "4096 87380 16777216"



cockroachdb:
  version: "24.3.2"  # Latest stable version
  user: "cockroach"
  group: "cockroach"
  base_dir: "/cockroachdb"
  # Data directory will be determined based on storage type
  data_dir: "{{ (storage.type == 'nfs') | ternary('/mnt' + storage.nfs.mount_path, storage.local.mount_path) }}"
  log_dir: "{{ (storage.type == 'nfs') | ternary('/mnt' + storage.nfs.log_path, storage.local.log_path) }}"
  certs_dir: "/var/lib/cockroachdb/certs"
  http_port: 8080
  sql_port: 26258
  cluster_port: 26257
  max_memory: "25%"  # Use 25% of available memory
  cache_size: "25%"  # Use 25% of available memory for cache
  max_disk_temp: "90%"  # Disk usage threshold for temp storage
  locality: "region=us-east,zone=us-east-1"  # Adjust for your environment
  security:
    admin_user: "root"
    admin_password: "{{ vault_cockroachdb_admin_password }}"
    ssl:
      enabled: true  # Enable SSL

rabbitmq:
  admin_user: "admin"
  web_admin_user: "web_admin"
  sysctl:
    fs.file-max: 500000
    kernel.msgmnb: 65536
    kernel.msgmax: 65536
  ssl:
    certs_dir: "/var/lib/rabbitmq/certs"
    certfile: "/var/lib/rabbitmq/certs/rabbitmq.crt"
    keyfile: "/var/lib/rabbitmq/certs/rabbitmq.key"
  data_dir: "{{ (storage.type == 'nfs') | ternary('/mnt' + storage.nfs.rabbitmq_path, storage.local.rabbitmq_path) }}"
monitoring:
  prometheus_node_exporter: true
  prometheus_port: 9100
  grafana_enabled: true

trusted_networks: "192.168.1.0/24"
admin_networks: "192.168.1.1/24"
monitoring_networks: "192.168.1.1/24"
ansible_user: "victor"

